spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://tiagodeoliveiravillalvamorel:davieisaac@helpdesk.yv0ylms.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=HelpDesk'
      auto-index-creation: true
springdoc:
  openapi:
    title: 'User Service API'
      description: 'Formação Backend Java Expert'
        version: '1.0.0'